export const START_AUTH_REQUEST = 'auth.START_AUTH_REQUEST';
export const START_AUTH_SUCCESS = 'auth.START_AUTH_SUCCESS';
export const START_AUTH_FAILURE = 'auth.START_AUTH_FAILURE';

export const COMPLETE_AUTH_REQUEST = 'auth.COMPLETE_AUTH_REQUEST';
export const COMPLETE_AUTH_SUCCESS = 'auth.COMPLETE_AUTH_SUCCESS';
export const COMPLETE_AUTH_FAILURE = 'auth.COMPLETE_AUTH_FAILURE';

export const LOGIN_REQUEST = 'auth.LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth.LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth.LOGIN_FAILURE';
