export const START_AUTH_REQUEST = 'auth.START_AUTH_REQUEST';
export const START_AUTH_SUCCESS = 'auth.START_AUTH_SUCCESS';
export const START_AUTH_FAILURE = 'auth.START_AUTH_FAILURE';

export const COMPLETE_AUTH_REQUEST = 'auth.COMPLETE_AUTH_REQUEST';
export const COMPLETE_AUTH_SUCCESS = 'auth.COMPLETE_AUTH_SUCCESS';
export const COMPLETE_AUTH_FAILURE = 'auth.COMPLETE_AUTH_FAILURE';
