export const SET_ETHER_ACCOUNT_REQUEST = 'account.SET_ETHER_ACCOUNT_REQUEST';
export const SET_ETHER_ACCOUNT_SUCCESS = 'account.SET_ETHER_ACCOUNT_SUCCESS';
export const SET_ETHER_ACCOUNT_FAILURE = 'account.SET_ETHER_ACCOUNT_FAILURE';
